name: CI/CD

on:
  push:
    tags:
      - 'v*' # Trigger on version tags
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test
      run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o turtle-${{ matrix.os }}-${{ matrix.arch }} turtle.go
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: turtle-binaries
        path: turtle-*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: turtle-binaries

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          turtle-*
        body: |
          Changes in this release:
          - Initial version
          - Automated builds